POST http://localhost:5000/api/wilders
Content-Type: application/json

{
    "name" : "Jane Doe",
    "city" : "Codesvile",
    "description" : "Lipsum",
    "grades" : [ {
            "id" : "1",
            "title" : "Typescript",
            "grade" : 1
        }, {
            "id" : "3",
            "title" : "Python",
            "grade" : 23
        } , {
            "id" : "4",
            "title" : "Rust",
            "grade" : 53
        }
        ]
}

###
GET http://localhost:5000/api/wilders

###
PUT http://localhost:5000/api/wilders
Content-Type: application/json

{
    "id": 1,
    "name": "Jane Doe",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus leo lorem, scelerisque at felis ultrices, tempus consequat nisi. Integer metus lectus, efficitur vitae sapien pellentesque, aliquam ultricies augue. Duis vehicula rutrum lorem, sed rutrum nunc iaculis placerat. Aenean id dapibus ligula. Etiam scelerisque purus id odio egestas, lobortis finibus diam venenatis. Donec ut nisl sed lacus tincidunt rutrum. Nulla non fermentum est, ut pretium lectus. Aenean et quam lacus. Nullam nec lacus facilisis, scelerisque dui id, cursus mi. Etiam in dolor ac ex auctor lobortis id vel orci.",
    "city": "TypeVille",
    "grades" : [
    {
        "id": 3,
        "title": "Typescript",
        "grade": 23
    },
    {
        "id": 4,
        "title": "Javascript",
        "grade": 53
    },
    {
        "id": 1,
        "title": "Python",
        "grade": 10
    },
    {
        "id": 2,
        "title": "Rust",
        "grade": 600
    }
]
}

###
POST http://localhost:5000/api/wilders/addSkill
Content-Type: application/json

{
    "wilderId" : 11,
    "skillId" : 2,
    "grade": 4
}

###
DELETE http://localhost:5000/api/wilders
Content-Type: application/json

{
    "id" : 3
}