POST http://localhost:5000/api/wilders
Content-Type: application/json

{
    "name" : "Jane Doe",
    "city" : "Codesvile",
    "description" : "Lipsum",
    "grades" : [ {
            "id" : "1",
            "title" : "Typescript",
            "grade" : 1
        }, {
            "id" : "3",
            "title" : "Python",
            "grade" : 23
        } , {
            "id" : "4",
            "title" : "Rust",
            "grade" : 53
        }
        ]
}

###
GET http://localhost:5000/api/wilders

###
PUT http://localhost:5000/api/wilders
Content-Type: application/json

{
    "id": 1,
    "name": "Jane Doe",
    "description": "Lorem Ipsum (...)",
    "city": "TypeVille",
    "grades": [
      {
        "id": 1,
        "grade": 10
      }, {
        "id": 2,
        "grade" : 600
      }
    ]
}

###
POST http://localhost:5000/api/wilders/addSkill
Content-Type: application/json

{
    "wilderId" : 11,
    "skillId" : 2,
    "grade": 4
}

###
DELETE http://localhost:5000/api/wilders
Content-Type: application/json

{
    "id" : 3
}